### ISSUE TITLE
Schema validation fails

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#293]
**Describe the bug**
Designer throws a schema validation failed error

**To Reproduce**

1. Go to form details
2. change title
3. save
4. designer server throws error

**Expected behavior**
Business as usual!

**Comment by endamccormack** [comment]
P2

**Comment by DavidBiddle** [comment]
I believe that the issue here is that:

- when no feedback form is set, FormDetails.tsx sets the `url` to `""`
- schema.ts defines `url` as `joi.string().optional()` for non-feedback forms, which allows `undefined` or a populated string, but not `""`

So the solution is either:

- Edit the schema to allow the empty string
- Edit FormDetails.tsx to set `url` to `undefined` instead of `""`

I'm happy to PR either of these depending on which is preferable.

**Comment by DavidBiddle** [comment]
@jenbutongit about to raise a PR for this - I've gone with editing the schema but it should be pretty straightforward to change to the other option if you think that's better.

**Comment by jenbutongit** [comment]
hey @DavidBiddle, sorry, totally missed the first comment! Yep, that was exactly what I was planning but never got round to. Thanks for sorting! ❤️
