### ISSUE TITLE
Gov Pay Redirect won't work if Runner's session is Strict

### ISSUE THREAD

**Issue by bertrandmc** [XGovFormBuilder/digital-form-builder#428]
**Describe the bug**

To perform a payment, the user is redirected to Gov Pay and once payment is processed, the user is redirected back to runner's `PAY_RETURN_URL`. If session is configured to `isSameSite: "Strict",`, then the redirect back request will not include the existing session cookie, with this the runner will generate a new session id and a new cache key (cache keys are `${sessionId}:${visitId}`), causing the previous session cached data to be lost, which includes the form submitted data, payment status etc.

**To Reproduce**

As a developer
1. Add logs to the session id and cache state (redis must be working)
2. Submit a form which requires a test payment and take note of the session id and cache state
3. Submit the payment 
4. When redirected back you will see that a new session id was generated and a new empty cache was created

**Expected behavior**
When redirected back from GovPay user should continue with the same session id created before being redirected to GovPay and form's cache should be available

**Repository**
- runner

This regression was introduced 4 days ago https://github.com/XGovFormBuilder/digital-form-builder/blame/master/runner/src/server/plugins/session.ts

**Solution**
`isSameSite: "Lax"

**Comment by bertrandmc** [comment]
Hi @endamccormack,
I could send a PR for this, but I wonder if this would affect the security requirements you have?

**Comment by jenbutongit** [comment]
FWIW - I really dislike having the cache key exposed in the url. We have to keep adding the query param every time the user is redirected. We don't need it at all... 

I'm suggesting we remove this chunk. it was used to distinguish between a feedback form (which is another form with a feedback flag). It's overkill, since we already have an id for both forms, we don't need a "visit id" also. Currently, we are pushing to redis `{ userKey: {...theirAnswers} }`, we can do `{ userKey: {formId: {...answersForThisForm}, otherForm: {...answersForAnother}}` instead.

**Comment by endamccormack** [comment]
@bertrandmc go ahead, it shouldn't be an issue, from my memory the same-site just needs to be set, it doesn't need to be set to strict.

**Comment by superafroman** [comment]
This looks fixed to me so closing.
