### ISSUE TITLE
Support dynamic values within JSON config

### ISSUE THREAD

**Issue by superafroman** [XGovFormBuilder/digital-form-builder#469]
**Is your feature request related to a problem? Please describe.**
Currently the JSON config cannot be reconfigured between environments. This causes issues for example when deploying a form using a test API key (e.g. GOV.UK Pay) and then wanting to deploy the same form using the production key - you need to reconfigure the form and deploy a new file, rather than promoting the signed off one.

**Describe the solution you'd like**
Support some form of variable replacement within the JSON file, e.g. `payApiKey: '${PAY_API_KEY:test_abc123}'`

**Comment by jenbutongit** [comment]
@superafroman maybe something like this? https://github.com/marketplace/actions/variable-substitution

**Comment by superafroman** [comment]
Yeah, but probably best to do at deploy / start up time within the runner, so the runner's environment specifies the replacements allowing secrets to be isolated and the packaged form to be the same across environments.

**Comment by jenbutongit** [comment]
@superafroman I already have a script happening on yarn runner build. It's checking if forms are out of date and throwing an error (so it should blow up a pipeline if you've got an incompatible form) 

Worth putting another one in there? 

 https://github.com/XGovFormBuilder/digital-form-builder/blob/master/runner/bin/run/check/check.js

**Comment by superafroman** [comment]
The issue with doing it on build is that we then need to rebuild when we want to change the environment. We would need to change the Dockerfile to start by executing `yarn runner build && yarn runner start`. Which makes start up that much slower because we're rebuilding the app. It also doesn't accomodate for publishing via /publish. The values sub only has to be done when the for is first loaded, so not a big task - can even do it prior to parsing the JSON and it becomes a simple find/replace in a string (depending how complicated we want the var replacement to be).

Actually this is an issue for that check-forms script as well - you don't, or shouldn't need to, build the runner when you want to package up a version with some form config to deploy. Ideally you just extend the base runner docker image and add your form config. So the check forms script will never run. If it was done when the form config is loaded you can crash the server with an error that the config doesn't match the runner version.

**Comment by jenbutongit** [comment]
We can move it to before starting the app, but not after and inside the server. 

I have it at build time because that happens first in our pipeline, but there is no reason why it shouldn't happen in two places. we have test forms/example forms that we have to load - we may as well check them and fail the build before it reaches a published docker image.

Thinking a few things..: 
1. The test key needs to be configured as an environment variable
2. we don't do any variable substitution/string replacement, if you are in preview mode (i.e should not be used for live), we change PayService.options to use the configured variable instead. 
3. We should really remove /publish from  the runner code since it's not really core functionality. imo it should be a plugin which you can switch out if you want to use the persistence API (pending..), in memory, or not included at all when the server initialised (like when you're in live/prod mode)

**Comment by jenbutongit** [comment]
paging @gstevenson

**Comment by jenbutongit** [comment]
@superafroman I wonder if an easier way is just to provide test and live api keys in the same object, and we use whichever key depending on the env environment? This applies to notify keys too. 

```.json5
{
  //...
  "payApiKey": {
    "test": "test_key"
    "prod": "prod_key"
  }
  //...
}

```
