### ISSUE TITLE
Designer tool not functioning

### ISSUE THREAD

**Issue by PRDFE** [XGovFormBuilder/digital-form-builder#679]
The Designer tool (https://digital-form-builder-designer.herokuapp.com/app) is not allowing you to create a new form.

**To Reproduce**

1. Go to 'https://digital-form-builder-designer.herokuapp.com/app'
2. Click on 'Create a new form' and 'Continue'
3. this shows the loading.... message for an extended period
4. then on 'https://digital-form-builder-designer.herokuapp.com/app/new' 
5. Enter the name for a new form then select next
6. the form then doesnt move you to the form builder

**Expected behavior**
 on 'https://digital-form-builder-designer.herokuapp.com/app/new' 
5. Enter the name for a new form then select next
6. the form then moves you to the form builder environment to start a design
**Screenshots**
![image](https://user-images.githubusercontent.com/92520646/137306386-e6dc001c-49a4-43b3-9fca-30279f58644e.png)

**Repository**

**Desktop (please complete the following information):**

- OS: W 10 enterprise
- Browser [edge]
- Version [94.0.992.47]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jenbutongit** [comment]
hey @PRDFE, sorry I couldn't get to this yesterday, I've been sick 😢 - this should be resolved now. 

This is a sandbox environment, and it gets refreshed every time there is a deploy. To keep costs down for this environment we use in-memory stores, this way we don't have to pay additional storage, like S3 or redis.

I believe what happened is that since there hasn't been any updates in a couple days, we haven't been able to clear out old forms and they've just piled on (FCDO have been using this as their building environment), so we've slowly run out of memory causing it to be slow.
